spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:15432/triviet
    username: triviet
    password: 0913825888
    driverClassName: org.postgresql.Driver
jwt:
  secret_key: Ly|E}#R),K`B$Br
  expiration: 1440000

